### PR TITLE
The big refactor

### PR DESCRIPTION
**Pull request by takase1121**
Here's a few refactors for the code:

1. the indentation is fixed to 4 spaces
2. fix weird `package.cpath` and add support for loading dlls
3. Use `config.plugins` instead of `config`
4. move subprocess IO to a thread (instead of in View:update)
5. Rename `get_char_size` to `get_screen_char_size` since it's ambiguous
6. Move terminal resize to `update()` instead of `draw()`
7. Do not draw spaces (`\r\n\t\v\l `)
8. Pass varargs in `keymap.on_key_pressed` (needed in master)
9. Return char as string instead of number (wchar_t encoding cannot be assumed, it **must** be converted by libc)
10. Removed `time` field in `tmt:write`
11. `get_screen` returns a linear array instead of a 2D array
12. Fix memory leak where `tmt->answer` will be discarded without freeing
13. Remove unused macros
14. Shorten code by using some convenient lua functions

There is way too much to cover so I might forgot something.

### CODE REVIEW

**Comment by ColonelPhantom** [comment]
Wow, thanks for the PRs! I'll probably be merging most of your changes, although I did notice that you modified lua_tmt.c quite a lot, which was actually an existing library.

For the Lua part, which is all I wrote more-or-less myself, most of what you did seems reasonable. I did notice that `invisble` will not work (I think): you index it by `char` but I'm pretty sure that Lua has it as an array. The exact syntax escapes me right now, but something like `invisible = { ["\r"] = true, ... }`

**Comment by takase1121** [comment]
I didn't know lua_tmt was the library from luarocks. Now it makes sense since a lot of boilerplate I removed are available for later lua versions (while lua lib authors tend to write more backwards compatible code). I honestly don't think it was an issue since the library is simple enough and for lite-xl we're only targetting 5.2 (which is basically what I base the code on) and 5.4 (in 2.1). In theory its only 5.4 because 2.0.x does not have official support for native extension. The situation was planned to be resolved on 2.1. 

> For the Lua part, which is all I wrote more-or-less myself, most of what you did seems reasonable. I did notice that `invisble` will not work (I think): you index it by `char` but I'm pretty sure that Lua has it as an array. The exact syntax escapes me right now, but something like `invisible = { ["\r"] = true, ... }`

Sorry, that was an oversight, I'll put a fix later.

**Comment by takase1121** [comment]
Currently one problem I could see is with full terminal redraw. With the default size of 80x24 it easily exceeds 2000 calls which will exhaust the command buffer.

**Comment by ColonelPhantom** [comment]
These changes are amazing! That said, it seems like this is more your plugin than mine at this point. Would it not maybe be better to make your version the 'main' version, and then I just add a link to yours in my repo?

**Comment by takase1121** [comment]
> These changes are amazing! That said, it seems like this is more your plugin than mine at this point. Would it not maybe be better to make your version the 'main' version, and then I just add a link to yours in my repo?

I'm honored! I am not against it, but I might not be able to maintain it actively.

**Comment by ColonelPhantom** [comment]
I have to admit that I have not read all the code yet, but I have tested the updated plugin.

For maintainership, I think adding you to this repo might be a good alternative. That way both of us can work on it.

**Pull request merged**
